import langid

def test_langid_european_languages():
    european_languages = {
        "fr": "Ce Petit guide de survie des étudiants est un ouvrage pratique conçu pour accompagner les étudiants universitaires et collégiaux dans leur parcours académique. Reconnaissant que la vie étudiante peut être à la fois exaltante et stressante, ce guide aborde de nombreux aspects pratiques souvent négligés dans les manuels scolaires traditionnels.",  # Français
        "en": "This Student Survival Guide is a practical book designed to support university and college students throughout their academic journey. Acknowledging that student life can be both exhilarating and stressful, this guide covers numerous practical aspects often overlooked in traditional textbooks.",  # Anglais
        "de": "Dieser Studenten-Überlebensleitfaden ist ein praktisches Buch, das Universitäts- und Hochschulstudenten während ihres akademischen Werdegangs unterstützt. Es erkennt an, dass das Studentenleben sowohl aufregend als auch stressig sein kann, und behandelt zahlreiche praktische Aspekte, die in traditionellen Lehrbüchern oft vernachlässigt werden.",  # Allemand
        "es": "Esta Guía de Supervivencia para Estudiantes es un libro práctico diseñado para acompañar a los estudiantes universitarios y de colegio en su trayectoria académica. Reconociendo que la vida estudiantil puede ser tanto emocionante como estresante, esta guía aborda numerosos aspectos prácticos que a menudo se pasan por alto en los libros de texto tradicionales.",  # Espagnol
        "it": "Questa Guida alla Sopravvivenza per Studenti è un libro pratico progettato per supportare gli studenti universitari e dei college nel loro percorso accademico. Riconoscendo che la vita da studente può essere sia esaltante che stressante, questa guida affronta numerosi aspetti pratici spesso trascurati nei manuali scolastici tradizionali.",  # Italien
        "pt": "Este Guia de Sobrevivência do Estudante é um livro prático projetado para apoiar os estudantes universitários e colegiais em sua jornada acadêmica. Reconhecendo que a vida estudantil pode ser tanto emocionante quanto estressante, este guia aborda numerosos aspectos práticos frequentemente negligenciados nos livros didáticos tradicionais.",  # Portugais
        "nl": "Deze Studenten Overlevingsgids is een praktisch boek ontworpen om universiteits- en hogeschoolstudenten te ondersteunen tijdens hun academische reis. Erkennend dat het studentenleven zowel opwindend als stressvol kan zijn, behandelt deze gids tal van praktische aspecten die vaak over het hoofd worden gezien in traditionele leerboeken.",  # Néerlandais
        "sv": "Denna Studentöverlevnadsguide är en praktisk bok utformad för att stödja universitets- och högskolestudenter under deras akademiska resa. Den erkänner att studentlivet kan vara både spännande och stressande och täcker många praktiska aspekter som ofta förbises i traditionella läroböcker.",  # Suédois
        "da": "Denne Studerendes Overlevelsesguide er en praktisk bog designet til at støtte universitets- og college-studerende gennem deres akademiske rejse. Den anerkender, at studielivet kan være både spændende og stressende, og dækker mange praktiske aspekter, der ofte overses i traditionelle lærebøger.",  # Danois
        "fi": "Tämä Student's Little Survival Guide on käytännön työ, joka on suunniteltu tukemaan yliopisto- ja korkeakouluopiskelijoita heidän akateemisella matkallaan. Ymmärtääkseen, että opiskelijaelämä voi olla sekä jännittävää että stressaavaa, tämä opas kattaa monia käytännön asioita, jotka jäävät usein huomiotta perinteisissä oppikirjoissa.",  # Finnois
        "no": "Denne Studentens lille overlevelsesguide er et praktisk arbeid designet for å støtte universitets- og høyskolestudenter i deres akademiske reise. Denne veiledningen erkjenner at studentlivet kan være både spennende og stressende, og dekker mange praktiske aspekter som ofte blir oversett i tradisjonelle lærebøker.",  # Norvégien
        "pl": "Niniejszy Mały poradnik przetrwania studenta jest praktycznym opracowaniem mającym na celu wspieranie studentów szkół wyższych i uniwersytetów w ich karierze akademickiej. Mając na uwadze, że życie studenckie może być zarówno ekscytujące, jak i stresujące, w tym przewodniku omówiono wiele praktycznych aspektów, często pomijanych w tradycyjnych podręcznikach.",  # Polonais
        "cs": "Tento Student's Little Survival Guide je praktickou prací navrženou na podporu univerzitních a vysokoškolských studentů na jejich akademické cestě. Tato příručka si uvědomuje, že studentský život může být vzrušující i stresující, a proto se zabývá mnoha praktickými aspekty, které jsou v tradičních učebnicích často opomíjeny.",  # Tchèque
        "hu": "Ez a Student's Little Survival Guide egy gyakorlati munka, amelynek célja az egyetemi és főiskolai hallgatók támogatása a tudományos útjukban. Felismerve, hogy a tanulói élet izgalmas és stresszes is lehet, ez az útmutató sok olyan gyakorlati szempontot tárgyal, amelyeket a hagyományos tankönyvek gyakran figyelmen kívül hagynak.",  # Hongrois
        "el": "Αυτός ο «Οδηγός Μικρής Επιβίωσης του Φοιτητή» είναι μια πρακτική εργασία που έχει σχεδιαστεί για να υποστηρίξει φοιτητές πανεπιστημίου και πανεπιστημίου στο ακαδημαϊκό τους ταξίδι. Αναγνωρίζοντας ότι η φοιτητική ζωή μπορεί να είναι συναρπαστική και αγχωτική, αυτός ο οδηγός καλύπτει πολλές πρακτικές πτυχές που συχνά παραβλέπονται στα παραδοσιακά σχολικά βιβλία.",  # Grec
        "ro": "Acest Micul ghid de supraviețuire al elevului este o lucrare practică concepută pentru a sprijini studenții universitari și de facultate în călătoria lor academică. Recunoscând că viața de student poate fi atât incitantă, cât și stresantă, acest ghid acoperă multe aspecte practice adesea trecute cu vederea în manualele tradiționale.",  # Roumain
        "bg": "Това Малко ръководство за оцеляване за студенти е практическа работа, предназначена да подпомогне студентите в университетите и колежите в тяхното академично пътуване. Признавайки, че студентският живот може да бъде едновременно вълнуващ и стресиращ, това ръководство обхваща много практически аспекти, често пренебрегвани в традиционните учебници.",  # Bulgare
        "sk": "Tento Student's Little Survival Guide je praktická práca určená na podporu študentov univerzít a vysokých škôl na ich akademickej ceste. Uvedomujúc si, že študentský život môže byť vzrušujúci aj stresujúci, táto príručka obsahuje mnohé praktické aspekty, ktoré sa v tradičných učebniciach často prehliadajú.",  # Slovaque
        "sl": "Ta Student's Little Survival Guide je praktično delo, namenjeno podpori študentom in študentom na njihovi akademski poti. Ob zavedanju, da je študentsko življenje lahko vznemirljivo in stresno, ta vodnik pokriva številne praktične vidike, ki so v tradicionalnih učbenikih pogosto spregledani.",  # Slovène
        "hr": "Ovaj Mali vodič za preživljavanje za studente praktično je djelo osmišljeno kao podrška studentima sveučilišta i koledža na njihovom akademskom putu. Prepoznajući da studentski život može biti i uzbudljiv i stresan, ovaj vodič pokriva mnoge praktične aspekte koji se često zanemaruju u tradicionalnim udžbenicima.",  # Croate
        "et": "See Little Student Survival Guide on praktiline töö, mille eesmärk on toetada ülikoolide ja kolledžite üliõpilasi nende akadeemilisel teekonnal. Tunnistades, et üliõpilaselu võib olla nii põnev kui ka stressirohke, käsitleb käesolev juhend paljusid praktilisi aspekte, mis traditsioonilistes õpikutes sageli tähelepanuta jäävad.",  # Estonien
        "lv": "Šis mazo studentu izdzīvošanas ceļvedis ir praktisks darbs, kas paredzēts, lai atbalstītu universitāšu un koledžu studentus viņu akadēmiskajā ceļā. Atzīstot, ka studentu dzīve var būt gan aizraujoša, gan saspringta, šajā rokasgrāmatā ir apskatīti daudzi praktiski aspekti, kas tradicionālajās mācību grāmatās bieži netiek ņemti vērā.",  # Letton
        "lt": "Šis mažojo studento išgyvenimo vadovas yra praktinis darbas, skirtas padėti universitetų ir kolegijų studentams jų akademinėje kelionėje. Pripažįstant, kad studentų gyvenimas gali būti ir įdomus, ir įtemptas, šiame vadove pateikiama daug praktinių aspektų, kurie tradiciniuose vadovėliuose dažnai nepastebimi.",  # Lituanien
        "mt": "Din il-Gwida tas-Sopravivenza tal-Istudenti Żgħar hija xogħol prattiku ddisinjat biex jappoġġa lill-istudenti universitarji u tal-kulleġġ fil-vjaġġ akkademiku tagħhom. Filwaqt li tirrikonoxxi li l-ħajja tal-istudenti tista’ tkun kemm eċċitanti kif ukoll stressanti, din il-gwida tkopri ħafna aspetti prattiċi ħafna drabi injorati fil-kotba tradizzjonali.",  # Maltais
        "is": "Þessi Little Student Survival Guide er hagnýt verk sem ætlað er að styðja háskóla- og háskólanemendur í fræðilegu ferðalagi þeirra. Með því að viðurkenna að líf stúdenta getur verið bæði spennandi og streituvaldandi, fjallar þessi handbók um marga hagnýta þætti sem oft gleymast í hefðbundnum kennslubókum.",  # Islandais
        "ga": "Is obair phraiticiúil é an Little Student Survival Guide seo atá deartha chun tacú le mic léinn ollscoile agus coláiste ina n-aistear acadúil. Ag aithint gur féidir le saol an mhic léinn a bheith spreagúil agus struis araon, clúdaíonn an treoir seo go leor gnéithe praiticiúla nach ndéantar dearmad orthu go minic sna téacsleabhair thraidisiúnta.",  # Irlandais
        "sq": "Ky Udhëzues i Mbijetesës së Studentëve të Vogël është një punë praktike e krijuar për të mbështetur studentët e universitetit dhe kolegjit në udhëtimin e tyre akademik. Duke pranuar se jeta studentore mund të jetë emocionuese dhe stresuese, ky udhëzues mbulon shumë aspekte praktike që shpesh anashkalohen në tekstet tradicionale.",  # Albanais
        "bs": "Ovaj vodič za preživljavanje malih studenata je praktičan rad osmišljen da podrži studente univerziteta i fakulteta na njihovom akademskom putu. Prepoznajući da studentski život može biti i uzbudljiv i stresan, ovaj vodič pokriva mnoge praktične aspekte koji se često zanemaruju u tradicionalnim udžbenicima.",  # Bosniaque
        "mk": "Овој водич за преживување на мали студенти е практично дело дизајнирано да ги поддржи студентите на универзитетите и факултетите во нивното академско патување. Признавајќи дека студентскиот живот може да биде и возбудлив и стресен, овој водич опфаќа многу практични аспекти кои често се занемаруваат во традиционалните учебници.",  # Macédonien
        "sr": "Овај водич за преживљавање малих студената је практичан рад дизајниран да подржи студенте универзитета и факултета на њиховом академском путу. Препознајући да студентски живот може бити и узбудљив и стресан, овај водич покрива многе практичне аспекте који се често занемарују у традиционалним уџбеницима.",  # Serbe
        "cy": "Mae’r Little Student Survival Guide hwn yn waith ymarferol sydd wedi’i gynllunio i gefnogi myfyrwyr prifysgol a choleg ar eu taith academaidd. Gan gydnabod y gall bywyd myfyriwr fod yn gyffrous ac yn straen, mae'r canllaw hwn yn ymdrin â llawer o agweddau ymarferol a anwybyddir yn aml mewn gwerslyfrau traddodiadol.",  # Gallois
        "be": "Гэты маленькі дапаможнік па выжыванні для студэнтаў - гэта практычная праца, прызначаная для падтрымкі студэнтаў універсітэтаў і каледжаў у іх навучальным шляху. Прызнаючы, што студэнцкае жыццё можа быць як захапляльным, так і напружаным, гэты дапаможнік ахоплівае многія практычныя аспекты, якія часта забываюць у традыцыйных падручніках.",  # Biélorusse
        "uk": "Цей маленький посібник із виживання для студентів — це практична робота, розроблена для підтримки студентів університетів і коледжів у їхній академічній подорожі. Визнаючи, що студентське життя може бути водночас захоплюючим і напруженим, цей посібник охоплює багато практичних аспектів, які часто забувають у традиційних підручниках."  # Ukrainien
    }
    
    correct_predictions = 0
    total_tests = len(european_languages)
    
    for lang_code, sentence in european_languages.items():
        detected_lang = langid.classify(sentence)[0]
        if detected_lang == lang_code:
            correct_predictions += 1
        print(f"Phrase: {sentence}\nLangue attendue: {lang_code} | Langue détectée: {detected_lang}\n")
    
    accuracy = (correct_predictions / total_tests) * 100
    print(f"\nPrécision de langid: {accuracy:.2f}%")

if __name__ == "__main__":
    test_langid_european_languages()
